import 'package:flutter/material.dart';

ColorScheme colorSchemaLight = ColorScheme.fromSeed(
  seedColor: const Color(0xff3f4945),
  primary: const Color(0xff006c4e),
  onPrimary: const Color(0xffffffff),
  primaryContainer: const Color(0xff86f8cb),
  onPrimaryContainer: const Color(0xff002115),
  secondary: const Color(0xff4c6358),
  onSecondary: const Color(0xffffffff),
  secondaryContainer: const Color(0xffcfe8da),
  onSecondaryContainer: const Color(0xff0a1f17),
  tertiary: const Color(0xff3e6374),
  onTertiary: const Color(0xffffffff),
  tertiaryContainer: const Color(0xffc2e8fd),
  onTertiaryContainer: const Color(0xff001f2a),
  error: const Color(0xffba1b1b),
  onError: const Color(0xffffffff),
  errorContainer: const Color(0xffffdad4),
  onErrorContainer: const Color(0xff410001),
  background: const Color(0xfffbfdf9),
  onBackground: const Color(0xff191c1a),
  surface: const Color(0xfffbfdf9),
  onSurface: const Color(0xff191c1a),
  outline: const Color(0xff6f7973),
  surfaceVariant: const Color(0xffdbe5de),
  onSurfaceVariant: const Color(0xff404944),
);
ColorScheme colorSchemaDark = ColorScheme.fromSeed(
  seedColor: const Color(0xff3f4945),
  primary: const Color(0xff68dbaf),
  onPrimary: const Color(0xff003826),
  primaryContainer: const Color(0xff005139),
  onPrimaryContainer: const Color(0xff86f8cb),
  secondary: const Color(0xffb3cdbf),
  onSecondary: const Color(0xff1e352b),
  secondaryContainer: const Color(0xff354b41),
  onSecondaryContainer: const Color(0xffcfe8da),
  tertiary: const Color(0xffa6cce0),
  onTertiary: const Color(0xff093544),
  tertiaryContainer: const Color(0xff254b5b),
  onTertiaryContainer: const Color(0xffc2e8fd),
  error: const Color(0xffffb4a9),
  onError: const Color(0xff680003),
  errorContainer: const Color(0xff930006),
  onErrorContainer: const Color(0xffffdad4),
  background: const Color(0xff191c1a),
  onBackground: const Color(0xffe1e3df),
  surface: const Color(0xff191c1a),
  onSurface: const Color(0xffe1e3df),
  outline: const Color(0xff8a938d),
  surfaceVariant: const Color(0xff404944),
  onSurfaceVariant: const Color(0xffbfc9c2),
);
